export const catalog = [
  // ---- Finance & Accounting (7) ----
  { name: "FinchBooks", category: "Accounting", description: "A leading UK online accounting platform. MTD-ready and designed to work smoothly with your accountant.", url: "https://example.com/finchbooks", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["finances-vat","admin"], industryTags: [], techComfort: 2, ukSpecific: true },
  { name: "LedgerLane", category: "Accounting", description: "A popular UK alternative to FinchBooks. Slightly cheaper entry point and strong for smaller businesses.", url: "https://example.com/ledgerlane", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["finances-vat","admin"], industryTags: [], techComfort: 2, ukSpecific: true },
  { name: "Tallyhive", category: "Accounting", description: "Free with several major UK business bank accounts. Beginner-friendly, MTD-ready.", url: "https://example.com/tallyhive", priceTier: "Free", minSize: 1, maxSize: 10, painTags: ["finances-vat","admin","cash-flow"], industryTags: [], techComfort: 1, ukSpecific: true },
  { name: "BookkeepBritannia", category: "Accounting", description: "Long-established UK accounting brand. Trusted by traditional businesses and most accountants.", url: "https://example.com/bookkeepbritannia", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["finances-vat","admin"], industryTags: [], techComfort: 2, ukSpecific: true },
  { name: "SnapReceipt", category: "Accounting", description: "Receipt and invoice scanning that plugs into FinchBooks, LedgerLane and BookkeepBritannia. Cuts admin pain.", url: "https://example.com/snapreceipt", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["admin","finances-vat"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "Nudgepay", category: "Accounting", description: "Automated, polite invoice chasing. Connects to your accounting tool and runs itself.", url: "https://example.com/nudgepay", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["cash-flow","getting-paid","admin"], industryTags: [], techComfort: 1, ukSpecific: true },
  { name: "Directly", category: "Accounting", description: "Takes direct debit from customers — the cheapest reliable way to get paid on time.", url: "https://example.com/directly", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["cash-flow","getting-paid"], industryTags: [], techComfort: 2, ukSpecific: true },


  // ---- Payroll & HR (5) ----
  { name: "PayPilot", category: "HR & Recruitment", description: "HMRC-recognised UK payroll software. One of the simplest 'proper' payroll tools, popular with accountants.", url: "https://example.com/paypilot", priceTier: "Low", minSize: 2, maxSize: 250, painTags: ["payroll"], industryTags: [], techComfort: 2, ukSpecific: true },
  { name: "Crewly HR", category: "HR & Recruitment", description: "Simple UK HR for small teams — holiday, sickness, reviews. Built for non-HR people.", url: "https://example.com/crewly", priceTier: "Low", minSize: 10, maxSize: 250, painTags: ["payroll","admin","keeping-staff"], industryTags: [], techComfort: 1, ukSpecific: true },
  { name: "Sproutly HR", category: "HR & Recruitment", description: "UK-founded, deliberately minimal HR for small teams. Generous free tier.", url: "https://example.com/sproutly", priceTier: "Free", minSize: 2, maxSize: 50, painTags: ["payroll","admin","keeping-staff"], industryTags: [], techComfort: 1, ukSpecific: true },
  { name: "Hireboard", category: "HR & Recruitment", description: "A widely used UK job board. Free to post basic listings — ideal for occasional hires.", url: "https://example.com/hireboard", priceTier: "Free", minSize: 2, maxSize: 20, painTags: ["finding-staff"], industryTags: [], techComfort: 1, ukSpecific: true },
  { name: "Talentline", category: "HR & Recruitment", description: "Proper applicant tracking system — job board posting, interviews, candidate pipeline.", url: "https://example.com/talentline", priceTier: "Mid", minSize: 20, maxSize: 250, painTags: ["finding-staff","admin"], industryTags: [], techComfort: 2, ukSpecific: false },


  // ---- Productivity & Docs (3) ----
  { name: "WorkSphere Lite", category: "Email & Productivity", description: "Email, web word processor, spreadsheets, slides, cloud storage and chat. Cloud-only, budget-friendly.", url: "https://example.com/worksphere-lite", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["admin","team-comms"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "WorkSphere Pro", category: "Email & Productivity", description: "Everything in Lite plus desktop apps for word processing, spreadsheets, slides and mail. For heavy document work.", url: "https://example.com/worksphere-pro", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["admin","team-comms"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "Cumulus Office", category: "Email & Productivity", description: "Cloud-first email, docs, drive and video meetings. Default for creative, freelance and remote-first businesses.", url: "https://example.com/cumulus-office", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["admin","team-comms"], industryTags: [], techComfort: 1, ukSpecific: false },


  // ---- Team Communication (3) ----
  { name: "Huddleroom", category: "Communication", description: "Chat, calls and meetings. Free standalone or bundled with WorkSphere.", url: "https://example.com/huddleroom", priceTier: "Free", minSize: 2, maxSize: 250, painTags: ["team-comms"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "Chatter", category: "Communication", description: "Team chat loved by creative, freelance and remote teams. Generous free tier for small teams.", url: "https://example.com/chatter", priceTier: "Free", minSize: 2, maxSize: 250, painTags: ["team-comms"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "Pingbox Business", category: "Communication", description: "Free and familiar. Formalises what tiny teams already do on messaging apps.", url: "https://example.com/pingbox", priceTier: "Free", minSize: 1, maxSize: 10, painTags: ["team-comms","customer-comms"], industryTags: [], techComfort: 1, ukSpecific: false },


  // ---- CRM & Sales (5) ----
  { name: "Reachly CRM", category: "CRM", description: "Generalist CRM with a generous free tier. Covers most small businesses out of the box.", url: "https://example.com/reachly", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers","retain-customers"], industryTags: [], techComfort: 2, ukSpecific: false },
  { name: "DealStream", category: "CRM", description: "Simple visual sales pipeline. Great for professional services, consultants and B2B sales.", url: "https://example.com/dealstream", priceTier: "Low", minSize: 1, maxSize: 50, painTags: ["new-customers"], industryTags: ["professional-services"], techComfort: 1, ukSpecific: false },
  { name: "OrbitCRM", category: "CRM", description: "Budget-friendly CRM with a broad feature suite. Clunky UX but powerful for the money.", url: "https://example.com/orbitcrm", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers","retain-customers"], industryTags: [], techComfort: 2, ukSpecific: false },
  { name: "Apex Sales Cloud", category: "CRM", description: "Enterprise-grade sales pipeline. For larger SMEs already deep in the WorkSphere ecosystem.", url: "https://example.com/apex-sales", priceTier: "High", minSize: 50, maxSize: 250, painTags: ["new-customers","retain-customers"], industryTags: ["professional-services"], techComfort: 3, ukSpecific: false },
  { name: "JobBoxx", category: "CRM", description: "Trade-specific job and customer management for plumbers, electricians, builders. Quotes, scheduling, invoicing from the van.", url: "https://example.com/jobboxx", priceTier: "Low", minSize: 1, maxSize: 50, painTags: ["new-customers","admin","bookings"], industryTags: ["trades"], techComfort: 1, ukSpecific: false },


  // ---- Website & E-commerce (5) ----
  { name: "Sitewright", category: "Website", description: "Drag-and-drop website builder. Friendliest starting point for non-techies.", url: "https://example.com/sitewright", priceTier: "Free", minSize: 1, maxSize: 50, painTags: ["website","new-customers"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "Studioframe", category: "Website", description: "Polished templates, elegant design. Great for creative, hospitality, health and wellness.", url: "https://example.com/studioframe", priceTier: "Low", minSize: 1, maxSize: 50, painTags: ["website","new-customers"], industryTags: ["creative","hospitality","health"], techComfort: 1, ukSpecific: false },
  { name: "Pressly", category: "Website", description: "Hosted, managed publishing platform. Middle ground — more flexible than Studioframe, simpler than self-hosting.", url: "https://example.com/pressly", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["website"], industryTags: [], techComfort: 2, ukSpecific: false },
  { name: "MerchantHub", category: "E-commerce", description: "Best-in-class hosted e-commerce. What you pick when selling online is the whole point of the business.", url: "https://example.com/merchanthub", priceTier: "Mid", minSize: 1, maxSize: 250, painTags: ["website","stock","new-customers"], industryTags: ["retail"], techComfort: 2, ukSpecific: false },
  { name: "ShopPress", category: "E-commerce", description: "E-commerce layered onto a self-hosted Pressly site. Flexible and cheaper long-term — but only for confident users.", url: "https://example.com/shoppress", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["website","stock"], industryTags: ["retail"], techComfort: 3, ukSpecific: false },


  // ---- Customer Bookings (4) ----
  { name: "WorkSphere Bookings", category: "Bookings", description: "Free with WorkSphere. Basic but solid customer booking tool.", url: "https://example.com/worksphere-bookings", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["bookings"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "Slotwise", category: "Bookings", description: "Dead-easy meeting scheduler. Default for consultants, freelancers and professional services.", url: "https://example.com/slotwise", priceTier: "Free", minSize: 1, maxSize: 50, painTags: ["bookings"], industryTags: ["professional-services"], techComfort: 1, ukSpecific: false },
  { name: "Bookbright", category: "Bookings", description: "Takes deposits, handles classes and packages, custom booking forms. For paid bookings.", url: "https://example.com/bookbright", priceTier: "Low", minSize: 1, maxSize: 50, painTags: ["bookings"], industryTags: [], techComfort: 2, ukSpecific: false },
  { name: "SalonSpot", category: "Bookings", description: "UK-dominant booking tool for hair, beauty, spas and wellness. Free because they take a card-processing fee.", url: "https://example.com/salonspot", priceTier: "Free", minSize: 1, maxSize: 50, painTags: ["bookings","new-customers"], industryTags: ["health"], techComfort: 1, ukSpecific: true },


  // ---- Staff Rotas (3) ----
  { name: "Shiftboard UK", category: "Staff Rotas", description: "UK-native rota software. Simplest option for cafés, shops and small teams.", url: "https://example.com/shiftboard-uk", priceTier: "Low", minSize: 2, maxSize: 50, painTags: ["staff-rotas","team-comms"], industryTags: ["hospitality","retail","health"], techComfort: 1, ukSpecific: true },
  { name: "Crewstack", category: "Staff Rotas", description: "Rotas plus time tracking, timesheets and payroll integration. Scales as the business grows.", url: "https://example.com/crewstack", priceTier: "Low", minSize: 2, maxSize: 250, painTags: ["staff-rotas","payroll","admin"], industryTags: ["hospitality","retail","health"], techComfort: 2, ukSpecific: false },
  { name: "RotaPlan", category: "Staff Rotas", description: "Rotas for hospitality groups. Good when the business has multiple sites.", url: "https://example.com/rotaplan", priceTier: "Low", minSize: 10, maxSize: 250, painTags: ["staff-rotas","admin"], industryTags: ["hospitality"], techComfort: 2, ukSpecific: false },


  // ---- Marketing (4) ----
  { name: "InboxBird", category: "Marketing", description: "Default email marketing tool. Free tier up to 500 contacts covers most starting SMEs.", url: "https://example.com/inboxbird", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers","retain-customers"], industryTags: [], techComfort: 2, ukSpecific: false },
  { name: "DesignDeck", category: "Marketing", description: "Design without a designer — social posts, flyers, cards, menus, simple videos. Universally loved.", url: "https://example.com/designdeck", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers","admin"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "SocialHub Pro", category: "Marketing", description: "Manages major social platforms in one place. Essential if they use any of them seriously.", url: "https://example.com/socialhub-pro", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers"], industryTags: [], techComfort: 2, ukSpecific: false },
  { name: "Postbridge", category: "Marketing", description: "Schedules posts across all the major social channels. Free tier for 3 channels.", url: "https://example.com/postbridge", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers"], industryTags: ["professional-services","creative"], techComfort: 1, ukSpecific: false },


  // ---- Retail & POS (3) ----
  { name: "Tappay", category: "E-commerce", description: "Cheapest card reader option. No monthly fee — pay a small percentage per transaction. Massive UK presence with market stalls, mobile traders and small cafés.", url: "https://example.com/tappay", priceTier: "Free", minSize: 1, maxSize: 10, painTags: ["getting-paid","stock"], industryTags: ["retail","hospitality","health"], techComfort: 1, ukSpecific: true },
  { name: "CardCub", category: "E-commerce", description: "No-subscription card reader. Pay per transaction. Integrates well with major online payment providers.", url: "https://example.com/cardcub", priceTier: "Free", minSize: 1, maxSize: 20, painTags: ["getting-paid","stock"], industryTags: ["retail","hospitality","health"], techComfort: 1, ukSpecific: false },
  { name: "TillBox Retail", category: "E-commerce", description: "Full point-of-sale system — inventory, staff accounts, sales reports. For proper shops, not mobile traders.", url: "https://example.com/tillbox-retail", priceTier: "Free", minSize: 2, maxSize: 100, painTags: ["stock","admin","getting-paid"], industryTags: ["retail"], techComfort: 2, ukSpecific: false },


  // ---- Security & Backup (4) ----
  { name: "KeyVault Free", category: "Email & Productivity", description: "Open-source password manager. Fantastic free tier — default for tight budgets.", url: "https://example.com/keyvault-free", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["security"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "SafeKey", category: "Email & Productivity", description: "Polished, business-friendly password manager. Better onboarding and sharing than free alternatives.", url: "https://example.com/safekey", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["security"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "WorkSphere Defender", category: "Email & Productivity", description: "Antivirus and device protection designed for small businesses. Natural pick if they're already on WorkSphere.", url: "https://example.com/worksphere-defender", priceTier: "Low", minSize: 2, maxSize: 250, painTags: ["security"], industryTags: [], techComfort: 2, ukSpecific: false },
  { name: "BackupBox", category: "Email & Productivity", description: "Cloud backup with unlimited storage per computer. Saves you when a laptop dies or ransomware hits.", url: "https://example.com/backupbox", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["security","admin"], industryTags: [], techComfort: 1, ukSpecific: false },


  // ---- Power-User Tools (3) ----
  { name: "Threadspace", category: "Email & Productivity", description: "All-in-one workspace — docs, project tracking, wiki, databases. Loved by creative freelancers and small digital teams.", url: "https://example.com/threadspace", priceTier: "Free", minSize: 1, maxSize: 50, painTags: ["admin","team-comms"], industryTags: ["creative"], techComfort: 3, ukSpecific: false },
  { name: "Connectly", category: "Email & Productivity", description: "The automation glue — connects tools so one action triggers another. Transformative once it clicks.", url: "https://example.com/connectly", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["admin"], industryTags: [], techComfort: 2, ukSpecific: false },
  { name: "Flowforge", category: "Email & Productivity", description: "Cheaper, more flexible Connectly alternative. For properly technical users.", url: "https://example.com/flowforge", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["admin"], industryTags: [], techComfort: 3, ukSpecific: false },


  // ---- Project Management (3) ----
  { name: "Kanbanboard", category: "Project Management", description: "Kanban boards — drag cards between 'To do / Doing / Done'. Dead easy. A gentle intro to task management.", url: "https://example.com/kanbanboard", priceTier: "Free", minSize: 2, maxSize: 50, painTags: ["admin","team-comms"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "Tasksprout", category: "Project Management", description: "Generous free tier, more features than Kanbanboard. Great for professional services and creative agencies.", url: "https://example.com/tasksprout", priceTier: "Free", minSize: 2, maxSize: 250, painTags: ["admin","team-comms"], industryTags: ["professional-services","creative"], techComfort: 2, ukSpecific: false },
  { name: "Stridework", category: "Project Management", description: "Polished, visual project management. Strong UK brand recognition. Good for established teams with budget.", url: "https://example.com/stridework", priceTier: "Low", minSize: 2, maxSize: 250, painTags: ["admin","team-comms"], industryTags: [], techComfort: 2, ukSpecific: false },
];
