// All 52 tools in your catalog. Each tool has tags that the scoring engine matches against quiz answers.

export const catalog = [
  // ---- Finance & Accounting (7) ----
  { name: "Xero", category: "Accounting", description: "UK market leader for online accounting. MTD-ready and works brilliantly with accountants.", url: "https://www.xero.com/uk/", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["finances-vat","admin"], industryTags: [], techComfort: 2, ukSpecific: true, trustScore: 4.1, trustReviews: 10844, trustUrl: "https://uk.trustpilot.com/review/www.xero.com" },
  { name: "QuickBooks Online (UK)", category: "Accounting", description: "Popular UK alternative to Xero. Slightly cheaper entry point, strong for smaller businesses.", url: "https://quickbooks.intuit.com/uk/", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["finances-vat","admin"], industryTags: [], techComfort: 2, ukSpecific: true, trustScore: 3.9, trustReviews: 16642, trustUrl: "https://uk.trustpilot.com/review/quickbooks.intuit.com" },
  { name: "FreeAgent", category: "Accounting", description: "Free with NatWest, Mettle, RBS or Ulster Bank business accounts. Beginner-friendly, MTD-ready.", url: "https://www.freeagent.com/", priceTier: "Free", minSize: 1, maxSize: 10, painTags: ["finances-vat","admin","cash-flow"], industryTags: [], techComfort: 1, ukSpecific: true, trustScore: 4.5, trustReviews: 2844, trustUrl: "https://uk.trustpilot.com/review/www.freeagent.com" },
  { name: "Sage Business Cloud Accounting", category: "Accounting", description: "Long-established UK brand. Trusted by traditional businesses and most accountants.", url: "https://www.sage.com/en-gb/sage-business-cloud/accounting/", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["finances-vat","admin"], industryTags: [], techComfort: 2, ukSpecific: true, trustScore: 4.0, trustReviews: 19559, trustUrl: "https://uk.trustpilot.com/review/sage.com" },
  { name: "Dext", category: "Accounting", description: "Receipt and invoice scanning that plugs into Xero, QuickBooks and Sage. Cuts admin pain.", url: "https://dext.com/uk", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["admin","finances-vat"], industryTags: [], techComfort: 1, ukSpecific: false, trustScore: 4.7, trustReviews: 1885, trustUrl: "https://uk.trustpilot.com/review/dext.com" },
  { name: "Chaser", category: "Accounting", description: "Automated, polite invoice chasing. Connects to your accounting tool and runs itself.", url: "https://www.chaserhq.com/", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["cash-flow","getting-paid","admin"], industryTags: [], techComfort: 1, ukSpecific: true },
  { name: "GoCardless", category: "Accounting", description: "Takes direct debit from customers — the cheapest reliable way to get paid on time.", url: "https://gocardless.com/en-gb/", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["cash-flow","getting-paid"], industryTags: [], techComfort: 2, ukSpecific: true, trustScore: 2.4, trustReviews: 2406, trustUrl: "https://uk.trustpilot.com/review/gocardless.com" },

  // ---- Payroll & HR (5) ----
  { name: "BrightPay", category: "HR & Recruitment", description: "HMRC-recognised UK payroll software. Simple of the 'proper' payroll tools, popular with accountants.", url: "https://www.brightpay.co.uk/", priceTier: "Low", minSize: 2, maxSize: 250, painTags: ["payroll"], industryTags: [], techComfort: 2, ukSpecific: true, trustScore: 4.1, trustReviews: 736, trustUrl: "https://uk.trustpilot.com/review/brightsg.com" },
  { name: "Breathe HR", category: "HR & Recruitment", description: "Simple UK HR for small teams — holiday, sickness, reviews. Built for non-HR people.", url: "https://www.breathehr.com/en-gb", priceTier: "Low", minSize: 10, maxSize: 250, painTags: ["payroll","admin","keeping-staff"], industryTags: [], techComfort: 1, ukSpecific: true, trustScore: 4.1, trustReviews: 133, trustUrl: "https://uk.trustpilot.com/review/breathehr.com" },
  { name: "CharlieHR", category: "HR & Recruitment", description: "UK-founded, deliberately minimal HR for small teams. Generous free tier.", url: "https://www.charliehr.com/", priceTier: "Free", minSize: 2, maxSize: 50, painTags: ["payroll","admin","keeping-staff"], industryTags: [], techComfort: 1, ukSpecific: true, trustScore: 3.2, trustReviews: 86, trustUrl: "https://uk.trustpilot.com/review/charliehr.com" },
  { name: "Indeed", category: "HR & Recruitment", description: "UK's most-used job board. Free to post basic listings — ideal for occasional hires.", url: "https://uk.indeed.com/", priceTier: "Free", minSize: 2, maxSize: 20, painTags: ["finding-staff"], industryTags: [], techComfort: 1, ukSpecific: true },
  { name: "Workable", category: "HR & Recruitment", description: "Proper applicant tracking system — job board posting, interviews, candidate pipeline.", url: "https://www.workable.com/", priceTier: "Mid", minSize: 20, maxSize: 250, painTags: ["finding-staff","admin"], industryTags: [], techComfort: 2, ukSpecific: false, trustScore: 3.3, trustReviews: 130, trustUrl: "https://uk.trustpilot.com/review/workable.com" },

  // ---- Productivity & Docs (3) ----
  { name: "Microsoft 365 Business Basic", category: "Email & Productivity", description: "Email, web Word/Excel/PowerPoint, OneDrive and Teams. Cloud-only, budget-friendly.", url: "https://www.microsoft.com/en-gb/microsoft-365/business/microsoft-365-business-basic", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["admin","team-comms"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "Microsoft 365 Business Standard", category: "Email & Productivity", description: "Everything in Basic plus desktop Word, Excel, PowerPoint and Outlook. For heavy document work.", url: "https://www.microsoft.com/en-gb/microsoft-365/business/microsoft-365-business-standard", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["admin","team-comms"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "Google Workspace", category: "Email & Productivity", description: "Gmail, Docs, Drive and Meet. Default for creative, freelance and remote-first businesses.", url: "https://workspace.google.com/intl/en_uk/", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["admin","team-comms"], industryTags: [], techComfort: 1, ukSpecific: false, trustScore: 1.3, trustReviews: 118, trustUrl: "https://uk.trustpilot.com/review/workspace.google.com" },

  // ---- Team Communication (3) ----
  { name: "Microsoft Teams", category: "Communication", description: "Chat, calls and meetings. Free standalone or bundled with Microsoft 365.", url: "https://www.microsoft.com/en-gb/microsoft-teams/group-chat-software", priceTier: "Free", minSize: 2, maxSize: 250, painTags: ["team-comms"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "Slack", category: "Communication", description: "Team chat loved by creative, freelance and remote teams. Generous free tier for small teams.", url: "https://slack.com/intl/en-gb/", priceTier: "Free", minSize: 2, maxSize: 250, painTags: ["team-comms"], industryTags: [], techComfort: 1, ukSpecific: false, trustScore: 2.5, trustReviews: 348, trustUrl: "https://uk.trustpilot.com/review/slack.com" },
  { name: "WhatsApp Business", category: "Communication", description: "Free and familiar. Formalises what tiny teams already do on phones.", url: "https://business.whatsapp.com/", priceTier: "Free", minSize: 1, maxSize: 10, painTags: ["team-comms","customer-comms"], industryTags: [], techComfort: 1, ukSpecific: false },

  // ---- CRM & Sales (5) ----
  { name: "HubSpot CRM", category: "CRM", description: "Generalist CRM with a generous free tier. Covers most small businesses out of the box.", url: "https://www.hubspot.com/products/crm", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers","retain-customers"], industryTags: [], techComfort: 2, ukSpecific: false, trustScore: 1.7, trustReviews: 1079, trustUrl: "https://uk.trustpilot.com/review/hubspot.com" },
  { name: "Pipedrive", category: "CRM", description: "Simple visual sales pipeline. Great for professional services, consultants and B2B sales.", url: "https://www.pipedrive.com/en-gb", priceTier: "Low", minSize: 1, maxSize: 50, painTags: ["new-customers"], industryTags: ["professional-services"], techComfort: 1, ukSpecific: false, trustScore: 4.5, trustReviews: 3290, trustUrl: "https://uk.trustpilot.com/review/pipedrive.com" },
  { name: "Zoho CRM", category: "CRM", description: "Budget-friendly CRM with a broad feature suite. Clunky UX but powerful for the money.", url: "https://www.zoho.com/en-gb/crm/", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers","retain-customers"], industryTags: [], techComfort: 2, ukSpecific: false, trustScore: 4.0, trustReviews: 5893, trustUrl: "https://uk.trustpilot.com/review/www.zoho.com" },
  { name: "Microsoft Dynamics 365 Sales", category: "CRM", description: "Enterprise-grade sales pipeline. For larger SMEs already deep in Microsoft 365.", url: "https://www.microsoft.com/en-gb/dynamics-365/products/sales", priceTier: "High", minSize: 50, maxSize: 250, painTags: ["new-customers","retain-customers"], industryTags: ["professional-services"], techComfort: 3, ukSpecific: false },
  { name: "ServiceM8", category: "CRM", description: "Trade-specific job and customer management for plumbers, electricians, builders. Quotes, scheduling, invoicing from the van.", url: "https://www.servicem8.com/uk/", priceTier: "Low", minSize: 1, maxSize: 50, painTags: ["new-customers","admin","bookings"], industryTags: ["trades"], techComfort: 1, ukSpecific: false, trustScore: 4.3, trustReviews: 101, trustUrl: "https://uk.trustpilot.com/review/www.servicem8.com" },

  // ---- Website & E-commerce (5) ----
  { name: "Wix", category: "Website", description: "Drag-and-drop website builder. Friendliest starting point for non-techies.", url: "https://www.wix.com/", priceTier: "Free", minSize: 1, maxSize: 50, painTags: ["website","new-customers"], industryTags: [], techComfort: 1, ukSpecific: false, trustScore: 3.5, trustReviews: 27120, trustUrl: "https://uk.trustpilot.com/review/www.wix.com" },
  { name: "Squarespace", category: "Website", description: "Polished templates, elegant design. Great for creative, hospitality, health and wellness.", url: "https://www.squarespace.com/", priceTier: "Low", minSize: 1, maxSize: 50, painTags: ["website","new-customers"], industryTags: ["creative","hospitality","health"], techComfort: 1, ukSpecific: false, trustScore: 3.2, trustReviews: 2793, trustUrl: "https://uk.trustpilot.com/review/www.squarespace.com" },
  { name: "WordPress.com", category: "Website", description: "Hosted, managed WordPress. Middle ground — more flexible than Squarespace, simpler than self-hosted WordPress.", url: "https://wordpress.com/", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["website"], industryTags: [], techComfort: 2, ukSpecific: false, trustScore: 3.6, trustReviews: 4028, trustUrl: "https://uk.trustpilot.com/review/www.wordpress.com" },
  { name: "Shopify", category: "E-commerce", description: "Best-in-class e-commerce. What you pick when selling online is the whole point of the business.", url: "https://www.shopify.com/uk", priceTier: "Mid", minSize: 1, maxSize: 250, painTags: ["website","stock","new-customers"], industryTags: ["retail"], techComfort: 2, ukSpecific: false, trustScore: 1.3, trustReviews: 4560, trustUrl: "https://uk.trustpilot.com/review/www.shopify.com" },
  { name: "WooCommerce", category: "E-commerce", description: "E-commerce layered onto self-hosted WordPress. Flexible and cheaper long-term — but only for confident users.", url: "https://woocommerce.com/", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["website","stock"], industryTags: ["retail"], techComfort: 3, ukSpecific: false, trustScore: 2.0, trustReviews: 134, trustUrl: "https://uk.trustpilot.com/review/woocommerce.com" },

  // ---- Customer Bookings (4) ----
  { name: "Microsoft Bookings", category: "Bookings", description: "Free with Microsoft 365. Basic but solid customer booking tool.", url: "https://www.microsoft.com/en-gb/microsoft-365/business/scheduling-and-booking-app", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["bookings"], industryTags: [], techComfort: 1, ukSpecific: false },
  { name: "Calendly", category: "Bookings", description: "Dead-easy meeting scheduler. Default for consultants, freelancers and professional services.", url: "https://calendly.com/", priceTier: "Free", minSize: 1, maxSize: 50, painTags: ["bookings"], industryTags: ["professional-services"], techComfort: 1, ukSpecific: false, trustScore: 3.0, trustReviews: 469, trustUrl: "https://uk.trustpilot.com/review/calendly.com" },
  { name: "Acuity Scheduling", category: "Bookings", description: "Takes deposits, handles classes and packages, custom booking forms. For paid bookings.", url: "https://acuityscheduling.com/", priceTier: "Low", minSize: 1, maxSize: 50, painTags: ["bookings"], industryTags: [], techComfort: 2, ukSpecific: false, trustScore: 3.8, trustReviews: 471, trustUrl: "https://uk.trustpilot.com/review/acuityscheduling.com" },
  { name: "Fresha", category: "Bookings", description: "UK-dominant booking tool for hair, beauty, spas and wellness. Free because they take a card-processing fee.", url: "https://www.fresha.com/for-business", priceTier: "Free", minSize: 1, maxSize: 50, painTags: ["bookings","new-customers"], industryTags: ["health"], techComfort: 1, ukSpecific: true, trustScore: 4.7, trustReviews: 5617, trustUrl: "https://uk.trustpilot.com/review/fresha.com" },

  // ---- Staff Rotas (3) ----
  { name: "RotaCloud", category: "Staff Rotas", description: "UK-native rota software. Simplest option for cafés, shops and small teams.", url: "https://rotacloud.com/", priceTier: "Low", minSize: 2, maxSize: 50, painTags: ["staff-rotas","team-comms"], industryTags: ["hospitality","retail","health"], techComfort: 1, ukSpecific: true, trustScore: 3.0, trustReviews: 60, trustUrl: "https://uk.trustpilot.com/review/rotacloud.com" },
  { name: "Deputy", category: "Staff Rotas", description: "Rotas plus time tracking, timesheets and payroll integration. Scales as the business grows.", url: "https://www.deputy.com/uk", priceTier: "Low", minSize: 2, maxSize: 250, painTags: ["staff-rotas","payroll","admin"], industryTags: ["hospitality","retail","health"], techComfort: 2, ukSpecific: false, trustScore: 3.0, trustReviews: 110, trustUrl: "https://uk.trustpilot.com/review/deputy.com" },
  { name: "Planday", category: "Staff Rotas", description: "Rotas for hospitality groups. Good when the business has multiple sites.", url: "https://www.planday.com/uk/", priceTier: "Low", minSize: 10, maxSize: 250, painTags: ["staff-rotas","admin"], industryTags: ["hospitality"], techComfort: 2, ukSpecific: false, trustScore: 4.7, trustReviews: 349, trustUrl: "https://uk.trustpilot.com/review/planday.com" },

  // ---- Marketing (4) ----
  { name: "Mailchimp", category: "Marketing", description: "Default email marketing tool. Free tier up to 500 contacts covers most starting SMEs.", url: "https://mailchimp.com/en-gb/", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers","retain-customers"], industryTags: [], techComfort: 2, ukSpecific: false, trustScore: 2.6, trustReviews: 1407, trustUrl: "https://uk.trustpilot.com/review/www.mailchimp.com" },
  { name: "Canva", category: "Marketing", description: "Design without a designer — social posts, flyers, cards, menus, simple videos. Universally loved.", url: "https://www.canva.com/en_gb/", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers","admin"], industryTags: [], techComfort: 1, ukSpecific: false, trustScore: 3.8, trustReviews: 4649, trustUrl: "https://uk.trustpilot.com/review/canva.com" },
  { name: "Meta Business Suite", category: "Marketing", description: "Manages Facebook and Instagram in one place. Essential if they use either platform.", url: "https://business.facebook.com/", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers"], industryTags: [], techComfort: 2, ukSpecific: false },
  { name: "Buffer", category: "Marketing", description: "Schedules posts across LinkedIn, X, TikTok, Pinterest and Meta. Free tier for 3 channels.", url: "https://buffer.com/", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["new-customers"], industryTags: ["professional-services","creative"], techComfort: 1, ukSpecific: false, trustScore: 3.1, trustReviews: 102, trustUrl: "https://uk.trustpilot.com/review/buffer.com" },

  // ---- Retail & POS (3) ----
  { name: "SumUp", category: "E-commerce", description: "Cheapest card reader option. No monthly fee — pay 1.69% per transaction. Massive UK presence with market stalls, mobile traders and small cafés.", url: "https://www.sumup.com/en-gb/", priceTier: "Free", minSize: 1, maxSize: 10, painTags: ["getting-paid","stock"], industryTags: ["retail","hospitality","health"], techComfort: 1, ukSpecific: true, trustScore: 4.1, trustReviews: 42433, trustUrl: "https://uk.trustpilot.com/review/sumup.com" },
  { name: "Zettle by PayPal", category: "E-commerce", description: "No subscription card reader. Pay per transaction. Integrates well with PayPal if they use it.", url: "https://www.zettle.com/gb", priceTier: "Free", minSize: 1, maxSize: 20, painTags: ["getting-paid","stock"], industryTags: ["retail","hospitality","health"], techComfort: 1, ukSpecific: false, trustScore: 3.4, trustReviews: 5601, trustUrl: "https://uk.trustpilot.com/review/zettle.com" },
  { name: "Square for Retail", category: "E-commerce", description: "Full point-of-sale system — inventory, staff accounts, sales reports. For proper shops, not mobile traders.", url: "https://squareup.com/gb/en/point-of-sale/retail", priceTier: "Free", minSize: 2, maxSize: 100, painTags: ["stock","admin","getting-paid"], industryTags: ["retail"], techComfort: 2, ukSpecific: false, trustScore: 4.1, trustReviews: 7299, trustUrl: "https://uk.trustpilot.com/review/squareup.com/us" },

  // ---- Security & Backup (4) ----
  { name: "Bitwarden", category: "Email & Productivity", description: "Open-source password manager. Fantastic free tier — default for tight budgets.", url: "https://bitwarden.com/", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["security"], industryTags: [], techComfort: 1, ukSpecific: false, trustScore: 3.6, trustReviews: 342, trustUrl: "https://uk.trustpilot.com/review/bitwarden.com" },
  { name: "1Password", category: "Email & Productivity", description: "Polished, business-friendly password manager. Better onboarding and sharing than free alternatives.", url: "https://1password.com/business", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["security"], industryTags: [], techComfort: 1, ukSpecific: false, trustScore: 4.1, trustReviews: 12354, trustUrl: "https://uk.trustpilot.com/review/1password.com" },
  { name: "Microsoft Defender for Business", category: "Email & Productivity", description: "Antivirus and device protection designed for small businesses. Natural pick if they're already in M365.", url: "https://www.microsoft.com/en-gb/security/business/microsoft-defender-for-business", priceTier: "Low", minSize: 2, maxSize: 250, painTags: ["security"], industryTags: [], techComfort: 2, ukSpecific: false },
  { name: "Backblaze", category: "Email & Productivity", description: "Cloud backup with unlimited storage per computer. Saves you when a laptop dies or ransomware hits.", url: "https://www.backblaze.com/", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["security","admin"], industryTags: [], techComfort: 1, ukSpecific: false, trustScore: 2.1, trustReviews: 218, trustUrl: "https://uk.trustpilot.com/review/www.backblaze.com" },

  // ---- Power-User Tools (3) ----
  { name: "Notion", category: "Email & Productivity", description: "All-in-one workspace — docs, project tracking, wiki, databases. Loved by creative freelancers and small digital teams.", url: "https://www.notion.so/", priceTier: "Free", minSize: 1, maxSize: 50, painTags: ["admin","team-comms"], industryTags: ["creative"], techComfort: 3, ukSpecific: false, trustScore: 2.4, trustReviews: 399, trustUrl: "https://uk.trustpilot.com/review/notion.so" },
  { name: "Zapier", category: "Email & Productivity", description: "The automation glue — connects tools so one action triggers another. Transformative once it clicks.", url: "https://zapier.com/", priceTier: "Low", minSize: 1, maxSize: 250, painTags: ["admin"], industryTags: [], techComfort: 2, ukSpecific: false, trustScore: 1.4, trustReviews: 292, trustUrl: "https://uk.trustpilot.com/review/zapier.com" },
  { name: "Make", category: "Email & Productivity", description: "Cheaper, more flexible Zapier alternative. For properly technical users.", url: "https://www.make.com/en", priceTier: "Free", minSize: 1, maxSize: 250, painTags: ["admin"], industryTags: [], techComfort: 3, ukSpecific: false, trustScore: 2.8, trustReviews: 158, trustUrl: "https://uk.trustpilot.com/review/make.com" },

  // ---- Project Management (3) ----
  { name: "Trello", category: "Project Management", description: "Kanban boards — drag cards between 'To do / Doing / Done'. Dead easy. A gentle intro to task management.", url: "https://trello.com/en-GB", priceTier: "Free", minSize: 2, maxSize: 50, painTags: ["admin","team-comms"], industryTags: [], techComfort: 1, ukSpecific: false, trustScore: 2.6, trustReviews: 212, trustUrl: "https://uk.trustpilot.com/review/trello.com" },
  { name: "Asana", category: "Project Management", description: "Generous free tier, more features than Trello. Great for professional services and creative agencies.", url: "https://asana.com/", priceTier: "Free", minSize: 2, maxSize: 250, painTags: ["admin","team-comms"], industryTags: ["professional-services","creative"], techComfort: 2, ukSpecific: false, trustScore: 1.6, trustReviews: 292, trustUrl: "https://uk.trustpilot.com/review/www.asana.com" },
  { name: "Monday.com", category: "Project Management", description: "Polished, visual project management. Strong UK brand recognition. Good for established teams with budget.", url: "https://monday.com/", priceTier: "Low", minSize: 2, maxSize: 250, painTags: ["admin","team-comms"], industryTags: [], techComfort: 2, ukSpecific: false, trustScore: 2.6, trustReviews: 3400, trustUrl: "https://uk.trustpilot.com/review/www.monday.com" },
];