// The 10 questions for the SME tech finder.
// Each option carries "tags" — pain areas it signals.
// The scoring engine uses these tags to match tools later.

export const questions = [
  {
    id: "size",
    title: "How many people work in the business?",
    subtitle: "Including you. Rough is fine.",
    type: "single",
    options: [
      { label: "Just me", value: 1, tags: [] },
      { label: "2–5 people", value: 3, tags: [] },
      { label: "6–20 people", value: 13, tags: [] },
      { label: "21–50 people", value: 35, tags: [] },
      { label: "51–250 people", value: 150, tags: [] },
    ],
  },
  {
    id: "industry",
    title: "What kind of business is it?",
    subtitle: "Pick the closest match — it helps us tailor recommendations.",
    type: "single",
    options: [
      { label: "Trades (plumber, electrician, builder, etc.)", value: "trades", tags: ["trades"] },
      { label: "Hospitality (café, restaurant, pub, hotel)", value: "hospitality", tags: ["hospitality"] },
      { label: "Retail (shop, online store)", value: "retail", tags: ["retail"] },
      { label: "Health & wellness (salon, clinic, gym, therapy)", value: "health", tags: ["health"] },
      { label: "Professional services (consulting, legal, accounting)", value: "professional-services", tags: ["professional-services"] },
      { label: "Creative (design, marketing, content, photography)", value: "creative", tags: ["creative"] },
      { label: "Something else", value: "other", tags: [] },
    ],
  },
  {
    id: "tech-comfort",
    title: "How comfortable are you with new tech?",
    subtitle: "Be honest — there's no wrong answer.",
    type: "single",
    options: [
      { label: "I want it dead simple. If it needs a manual, I'm out.", value: 1, tags: [] },
      { label: "I'll figure it out if it saves me time.", value: 2, tags: [] },
      { label: "I'm fine wiring tools together — bring it on.", value: 3, tags: [] },
    ],
  },
  {
    id: "biggest-pain",
    title: "What drives you most mad right now?",
    subtitle: "Pick up to 3.",
    type: "multi",
    max: 3,
    options: [
      { label: "Chasing late payments", value: "cash-flow", tags: ["cash-flow", "getting-paid"] },
      { label: "Finance, VAT and tax admin", value: "finances-vat", tags: ["finances-vat"] },
      { label: "Endless paperwork & admin", value: "admin", tags: ["admin"] },
      { label: "Finding new customers", value: "new-customers", tags: ["new-customers"] },
      { label: "Keeping the customers I have", value: "retain-customers", tags: ["retain-customers"] },
      { label: "Customer bookings / appointments", value: "bookings", tags: ["bookings"] },
      { label: "Staff rotas & scheduling", value: "staff-rotas", tags: ["staff-rotas"] },
      { label: "Hiring people", value: "finding-staff", tags: ["finding-staff"] },
      { label: "Keeping the staff I have happy", value: "keeping-staff", tags: ["keeping-staff"] },
      { label: "Payroll & HR admin", value: "payroll", tags: ["payroll"] },
      { label: "Stock / inventory", value: "stock", tags: ["stock"] },
      { label: "Team communication", value: "team-comms", tags: ["team-comms"] },
      { label: "Talking to customers", value: "customer-comms", tags: ["customer-comms"] },
      { label: "I don't have a website / mine is awful", value: "website", tags: ["website"] },
      { label: "Worrying about cyber security & data loss", value: "security", tags: ["security"] },
    ],
  },
  {
    id: "where-time-goes",
    title: "Where does your time disappear each week?",
    subtitle: "The bit you wish you could just press a button on.",
    type: "single",
    options: [
      { label: "Admin & paperwork", value: "admin", tags: ["admin"] },
      { label: "Customer-facing work (calls, emails, bookings)", value: "customer-comms", tags: ["customer-comms", "bookings"] },
      { label: "Finances & invoicing", value: "finances-vat", tags: ["finances-vat", "getting-paid"] },
      { label: "Managing staff", value: "staff-rotas", tags: ["staff-rotas", "payroll"] },
      { label: "Marketing & social media", value: "new-customers", tags: ["new-customers"] },
      { label: "I don't have a clear answer — it just goes", value: "unclear", tags: ["admin"] },    
    ],
  },
  {
    id: "current-stack",
    title: "What do you already use?",
    subtitle: "Tick anything that applies.",
    type: "multi",
    options: [
      { label: "Microsoft 365 (Outlook, Word, Excel)", value: "m365", tags: [] },
      { label: "Google Workspace (Gmail, Docs)", value: "google", tags: [] },
      { label: "An accounting tool (Xero, QuickBooks, Sage, FreeAgent)", value: "accounting", tags: [] },
      { label: "A CRM (HubSpot, Pipedrive, etc.)", value: "crm", tags: [] },
      { label: "Card reader (SumUp, Zettle, Square)", value: "card-reader", tags: [] },
      { label: "Booking system (Calendly, Acuity, Fresha)", value: "bookings", tags: [] },
      { label: "Honestly? Email and a spreadsheet.", value: "minimal", tags: ["admin"] },
    ],
  },
  {
    id: "growth-stage",
    title: "What stage is the business at?",
    subtitle: "",
    type: "single",
    options: [
      { label: "Just starting out", value: "startup", tags: ["website", "new-customers"] },
      { label: "Steady — ticking along nicely", value: "steady", tags: [] },
      { label: "Growing fast — struggling to keep up", value: "growing", tags: ["admin", "staff-rotas"] },
      { label: "Stuck — want to grow but can't crack it", value: "stuck", tags: ["new-customers"] },
    ],
  },
  {
    id: "budget",
    title: "What's the monthly software budget?",
    subtitle: "Total, across everything. A rough idea is fine.",
    type: "single",
    options: [
      { label: "As close to free as possible", value: "free", tags: [] },
      { label: "Under £50/month", value: "low", tags: [] },
      { label: "£50–200/month", value: "mid", tags: [] },
      { label: "£200+/month — I'll pay for the right thing", value: "high", tags: [] },
    ],
  },
  {
    id: "decision-style",
    title: "When picking new tools, what matters most?",
    subtitle: "",
    type: "single",
    options: [
      { label: "Cheap or free", value: "price", tags: [] },
      { label: "Easy to learn", value: "simple", tags: [] },
      { label: "Trusted UK brand", value: "uk-brand", tags: [] },
      { label: "Best features for the money", value: "features", tags: [] },
    ],
  },
  {
    id: "biggest-win",
    title: "If one thing got fixed tomorrow, which would change your life most?",
    subtitle: "Last one — pick the single biggest win.",
    type: "single",
    options: [
      { label: "More money in the bank, faster", value: "cash-flow", tags: ["cash-flow", "getting-paid"] },
      { label: "Less paperwork eating my evenings", value: "admin", tags: ["admin"] },
      { label: "More customers walking through the door", value: "new-customers", tags: ["new-customers"] },
      { label: "Staff sorted — rotas, payroll, hiring", value: "staff-rotas", tags: ["staff-rotas", "payroll", "finding-staff"] },
      { label: "A website I'm not embarrassed by", value: "website", tags: ["website"] },
      { label: "Confidence I won't get hacked or lose my data", value: "security", tags: ["security"] },
    ],
  },
];